export enum MenuType {
  None = 0,
  DashBoard = 1,
  BookingSummay = 2,
  AWBStackManagement = 3,
  PalletManagement = 4,
  Airport = 5,
  Sector = 6,
  Aircraft = 7,
  Flight = 8,
  FlightSchedule = 9,
  Rate = 10,
  UserManagement = 11,
  Notification=12,
  MasterSchedule=13,
  LinkAircraft=14,
  FleetReport=15,
  ULDMaster=16,
  StandByCargo=17,
  Messaging=18,
  ManageUser = 19,
  TrackBooking = 20,
  AgentBooking =21,
  TruckMaster = 22
}

export interface PackageAudit {
  packageId: string;
  packageNumber: string;
  collectedDate: string;
  packageStatus: number;
  awb: number;
  flightNumber: string;
  flightDate:Date | null;
}

export enum SectorType {
  None = 0,
  Domestic = 1,
  International = 2
}

export enum BookingSummaryType {
  None = 0,
  OnSeat = 1,
  UnderSeat = 2,
  Overhead = 3
}

export enum CargoPositionType {
  None = 0,
  OnFloor = 1,
  OnSeat = 2,
  UnderSeat = 3,
  Overhead = 4
}

export enum AircraftTypes {
  None = 0,
  B7879 = 1,
  A320200 = 2,
  B737400 = 3,
  B737800 = 4,
  B737300 = 5,
}

export enum AircraftSubTypes {
  None = 0,
  B7879TypeOne = 1,
  A320200TypeOne = 2,
  B737400TypeOne = 3,
  B737800TypeOne = 4,
  B737300TypeOne = 5,
}


export enum AircraftConfigType {
  None = 0,
  P2C = 1,
  Freighter = 2,
}

export enum AircraftStatus {
  None = 0,
  Charter = 1,
  Schedule = 2,
  Maintenance = 3,
}

export enum AircraftActiveTypes {
  None = 0,
  Active = 1,
  Inactive = 2
}

export enum LoaderImageSize {
  Small = 1,
  Medium = 2,
  Large = 3
}

export enum UnitType {
  None = 0,
  Length = 1,
  Mass = 2
}

export enum FlightScheduleStatus {
  None = 0,
  OnTime = 1,
  Delayed = 2
}

export enum WeightType {
  None = 0,
  M = 1,
  Minus45K = 2,
  Plus45K = 3,
  Plus100K = 4,
  Plus300K = 5,
  Plus500K = 6,
  Plus1000K = 7
}

export enum BookingStatus {
  None = 0,
  Booking_Made = 10,
  AWB_Added = 20,
  Cargo_Received = 30,
  IndestinationWarehouse= 35,
  Off_Loaded = 40,
  Partialy_Dispatched = 45,
  Flight_Dispatched = 50,
  Partialy_Arrived = 55,
  Flight_Arrived = 60,
  Cancelled = 70,
  Accepted_for_Flight = 80,
  Partshipment_for_Flight = 75,
  TruckForDelivery = 85,
  Deliverd = 90
}

export enum AWBStatus {
  None = 0,
  Pending = 1,
  AddedAWB = 2
}

export enum VerifyStatus {
  None = 0,
  ActualLoad = 1,
  OffLoad = 2,
  Dispatched = 3,
  Deleted = 4,
  CargoNotDispatched = 5
}

export enum AWBNumberStatus {
  None = 0,
  All = 1,
  Available = 2,
  Used = 3
}

export enum CargoAgentStatus {
  None = 0,
  Pending = 1,
  Active = 2,
  Suspended = 3
}

export enum CalendarType
{
    None = 0,
    Daily = 1,
    Weekly = 2,
    Monthly = 3,
}

export enum ScheduleStatus
{
    None = 0,
    Schedule = 1,
    Chartered = 2,
    Maintainance = 3,
}

export enum LinkAircraftFliterStatus {
  None = 0,
  Pending = 1,
  PartiallyCompleted = 2,
  Completed = 3
}

export enum MasterSheduleReportType {
  None = 0,
  IdleTimeReport = 1,
  Running = 2
}

export enum RateType{
  None=0,
  SpotRate =1,
  PromotionalRate=2,
  ContractRate=3,
  MarketPublishRate=4
}

export enum CargoType{
  None=0,
  General =1,
  DGR =2
}
export enum AssignAircraftViewType {
  None = 0,
  History = 1,
  UpcomingFlight =2
}

export enum RateViewType{
  None=0,
  Rate =1,
  Other=2,
}

export enum StandByCargoType {
  None = 0,
  NotReceived = 1,
  Offload = 2
}

export enum ULDType
{
    None = 0,
    Pallet = 1,
    Container = 2
}

export enum ULDOwnershipType
{
    None = 0,
    OwnByAirline = 1,
    Other = 2
}

export enum ULDLocateStatus
{
    None = 0,
    OnGround = 1,
    OnBoard = 2,
    Maintenance = 3,
    Lend = 4,
}


export enum ULDStatus
{
    None = 0,
    ULDPacked = 1,
    Flightloaded = 2,
    ULDUnpacked = 3,
}

export enum VerifyInputBase
{
  None = 0,
  FromHistory = 1,
  FromUpcoming = 2
}

export enum UserRole
{
    None = 0,
    BookingAdmin =1,
    BackofficeAdmin = 2,
    WarehouseAdmin = 3,
    BookingUser = 4,
    BackofficeUser = 5,
    WarehouseUser = 6,
    TruckDriver = 7
}

export enum AccessPortalLevel
{
    None = 0,
    Booking = 1,
    Backoffice = 2,
    WareHouse = 3
}

export enum UserStatus
{
    None = 0,
    Pending = 1, // not new password created. still autogenerated.
    Active = 2,
    Suspended = 3
}

export enum PackageItemCategory {
  None = 0,
  General = 1,
  Animal = 2,
  Artwork = 3,
  Dgr = 4
}
export enum PackageItemStatus {
  Booking_Made = 0,
  Picked_Up = 1,
  Returned = 2,
  Cargo_Received = 3,
  AcceptedForFlight = 4,
  Offloaded = 5,
  FlightDispatched = 6,
  Arrived = 7,
  InDestinationWarehouse = 8,
  TruckForDelivery = 9,
  Delivered = 10,
  Pending = 11,
  None = 12,
}




